# .gitlab-ci.yml
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA

image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_backend:
  stage: build
  script:
    # build from the 'rezimk' directory
    - docker build -t "$BACKEND_IMAGE" rezimk
    - docker push "$BACKEND_IMAGE"

build_frontend:
  stage: build
  script:
    # build from the 'frontend' directory
    - docker build -t "$FRONTEND_IMAGE" frontend/rezimk
    - docker push "$FRONTEND_IMAGE"

test_integration:
  stage: test
  script:
    - docker-compose up -d
    - sleep 20
    - curl --fail http://localhost:8080/actuator/health
    - curl --fail http://localhost:4200
    - docker-compose down

deploy_prod:
  stage: deploy
  only:
    - main
  script:
    - docker pull "$BACKEND_IMAGE"
    - docker pull "$FRONTEND_IMAGE"
    - docker-compose down || true
    - docker-compose up -d