services:
  backend:
    build:
      context: ./rezimk
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/rezimk
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zdravo
      POSTGRES_DB: rezi_mk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
