# Stage 1: build the Angular app
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: serve with Nginx
FROM nginx:alpine

# Remove default html
RUN rm -rf /usr/share/nginx/html/*

# Copy built files
COPY --from=builder /app/dist/rezimk /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]